### ISSUE TITLE
Minimal resources required for constrained environments

### ISSUE THREAD

**Issue by willowmck** [solo-io/solo-cop#40]
Some customers are dealing with constrained environments and need sensible defaults for limits for the control plane/data plane.

Could we run a standard performance test in constrained environment to establish minimal requirements?

**Comment by ably77** [comment]
Size and Memory requirements are documented here: https://docs.solo.io/gloo-mesh-enterprise/main/setup/system-requirements/#size-and-memory
```
The minimum recommended size for each cluster in your setup is at least 2vCPU and 8GB of memory per node.

For a more robust service mesh setup, the following sizes are recommended:

Management cluster nodes - 2vCPU and 8GB memory
Workload cluster nodes - 4vCPU and 16GB memory
```
