### ISSUE TITLE
Zero-downtime Gloo Mesh upgrade

### ISSUE THREAD

**Issue by willowmck** [solo-io/solo-cop#9]
Detail with source assets how to go about a zero-downtime Gloo Mesh upgrade

**Comment by artberger** [comment]
Related customer doc, right now, we don't promise zero downtime upgrades, so we could update the docs, too: https://docs.solo.io/gloo-mesh-enterprise/main/operations/upgrading/

**Comment by willowmck** [comment]
@willowmck - review doc steps and confirm

**Comment by willowmck** [comment]
@artberger - looks good!  I would only suggest that there be a note in Step 3 to pass any customized values to helm with --values.  Other than that, it worked flawlessly.

**Comment by artberger** [comment]
Thanks @willowmck , I added this in a doc fixes PR here: https://github.com/solo-io/gloo-mesh-enterprise/pull/2220/commits/b8572afa8bbd20fd515ba50393e50efb112b2a22

**Comment by willowmck** [comment]
Perfect!
